---
name: Catalyst-View-GD
version: 0.01
author:
  - 'Stevan Little E<lt>stevan.little@iinteractive.comE<gt>'
abstract: A Catalyst View for GD images
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst::Runtime: 0
  GD: 0
build_requires:
  Test::Exception: 0.21
  Test::Image::GD: 0.03
  Test::More: 0.62
provides:
  Catalyst::View::GD:
    file: lib/Catalyst/View/GD.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
